spring:
  security:
    oauth2:
      client:
        registration:
          naver: #개발자 검수를 해야하는데, 서비스 오픈 제가 임의로 등록한 선호님 예빈님 유리님 3명 개발자 검수 완료
            client-id: 9BxZLVQbdFZ0YDig4Gho
            client-secret: gS25x8fac3
            redirect-uri: http://localhost:8080/auth/oauth/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: 1d39dcddb137cd2f16d86df13e791db0
            client-secret: tscbTFVJlByDyErM6TIDcRZKi32SIph7
            redirect-uri: http://localhost:8080/auth/oauth/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
